# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 945f4a3a74dbe0ec02c02f4fb59f7e130fd9deda2178a4f95c257d81b41d230a6a3a7d0145a0b8305474692c516c7c64da00c31bf2695d237407ec8d5fb27d7b

test:
  secret_key_base: 7ab1babb823bfe264e395f515ff7566ce1e4c5b6877d399aeb77a0826089f3a7edf1ef954fbb373299cef09c1dc6a55537dc226f3787717be561db62ae244f49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
